{% set name = "FMJPEG2KOJ" %}
{% set version = "1.0.3" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/DraconPern/{{ name | lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c5b203ec580cab6fbd92c24712e987e960bda45638d4c2061d0b15d5d520ab42

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - dcmtk
    - openjpeg
    - m2-patch  # [win]

test:
  commands:
    - test -f $PREFIX/include/fmjpeg2k/djdecode.h  # [unix]
    - if not exist %LIBRARY_INC%\\fmjpeg2k\\djdecode.h exit 1  # [win]
    - test -f $PREFIX/lib/libfmjpeg2k.so.1  # [linux]
    - test -f $PREFIX/lib/libfmjpeg2k.1.dylib  # [mac]
    - if not exist %LIBRARY_BIN%\\fmjpeg2k.dll exit 1  # [win]
    - test -f $PREFIX/lib/cmake/fmjpeg2k/fmjpeg2kConfig.cmake  # [unix]
    - if not exist %LIBRARY_LIB%\\cmake\\fmjpeg2k\\fmjpeg2kConfig.cmake exit 1  # [win]


about:
  home: https://github.com/DraconPern/fmjpeg2koj
  license:  Apache-2.0
  license_file: LICENSE
  summary:  JPEG2000 codec for DCMTK using openjpeg 

extra:
  recipe-maintainers:
    - sameeul
